export {
    AppStoreIcon,
    AppGalleryIcon,
    RuStoreIcon,
    GooglePlayIcon,
    VkIcon,
    TelegramIcon,
    ArrowRightIcon,
    BioIcon,
    FeedbackIcon,
    OnlineCallIcon,
    VisuallyImpairedIcon,
    ChevronIcon,
    PinIcon,
    InternetBankIcon,
    SearchIcon,
    CloseIcon,
    storeIcons,
    socialIcons
} from './Icons'
